# Generated by Django 5.2.1 on 2025-05-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentales',
            name='oner_mobile_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
